<?php
return [

    /**
     * Set factory classes. Using Phooty\Orm entities by default.
     */
    'factories' => [
        'player' => Phooty\Crawler\Factory\Orm\PlayerFactory::class,
        'team' => Phooty\Crawler\Factory\Orm\TeamFactory::class,
        'roster.player' => Phooty\Crawler\Factory\Orm\RosterPlayerFactory::class,
        'stats' => Phooty\Crawler\Factory\Orm\StatsFactory::class,
    ],


    'teams' => [
        'AD' => [
            'short' => 'ad',
            'city' => 'Adelaide',
            'name' => 'Crows'
        ],
        'BL' => ['short' => 'bl', 'city' => 'Brisbane', 'name' => 'Lions'],
        'CA' => ['short' => 'ca', 'city' => 'Carlton', 'name' => 'Blues'],
        'CW' => ['short' => 'cw', 'city' => 'Collingwood', 'name' => 'Magpies'],
        'ES' => ['short' => 'es', 'city' => 'Essendon', 'name' => 'Bombers'],
        'FR' => ['short' => 'fr', 'city' => 'Fremantle', 'name' => 'Dockers'],
        'GC' => ['short' => 'gc', 'city' => 'Gold Coast', 'name' => 'Suns'],
        'GE' => ['short' => 'ge', 'city' => 'Geelong', 'name' => 'Cats'],
        'GW' => ['short' => 'gw', 'city' => 'Greater Western Sydney', 'name' => 'Giants'],
        'HW' => ['short' => 'hw', 'city' => 'Hawthorn', 'name' => 'Hawks'],
        'ME' => ['short' => 'me', 'city' => 'Melbourne', 'name' => 'Demons'],
        'NM' => ['short' => 'nm', 'city' => 'North Melbourne', 'name' => 'Kangaroos'],
        'PA' => ['short' => 'pa', 'city' => 'Port Adelaide', 'name' => 'Power'],
        'RI' => ['short' => 'ri', 'city' => 'Richmond', 'name' => 'Tigers'],
        'SK' => ['short' => 'sk', 'city' => 'St Kilda', 'name' => 'Saints'],
        'SY' => ['short' => 'sy', 'city' => 'Sydney', 'name' => 'Swans'],
        'WB' => ['short' => 'wb', 'city' => 'Western', 'name' => 'Bulldogs'],
        'WC' => ['short' => 'wc', 'city' => 'West Coast', 'name' => 'Eagles'],
        'UN' => ['short' => 'un', 'city' => 'University', 'name' => ''],
        'FI' => ['short' => 'fi', 'city' => 'Fitzroy', 'name' => 'Lions'],
        'BB' => ['short' => 'bb', 'city' => 'Brisbane', 'name' => 'Bears'],
        'SM' => ['short' => 'sm', 'city' => 'South Melbourne', 'name' => 'Swans']
    ],

    
    'aliases' => [
        'crows' => 'AD',
        'adelaide' => 'AD',
        'brissy' => 'BL',
        'brisbane' => 'BL',
        'brisbane lions' => 'BL',
        'lions' => 'BL',
        'blues' => 'CA',
        'carlton' => 'CA',
        'navy blues' => 'CA',
        'pies' => 'CW',
        'maggies' => 'CW',
        'collingwood' => 'CW',
        'magpies' => 'CW',
        'dons' => 'ES',
        'bombers' => 'ES',
        'essendon' => 'ES',
        'dockers' => 'FR',
        'freo' => 'FR',
        'fremantle' => 'FR',
        'gold coast' => 'GC',
        'suns' => 'GC',
        'cats' => 'GE',
        'geelong' => 'GE',
        'giants' => 'GW',
        'gw sydney' => 'GW',
        'greater western sydney' => 'GW',
        'gws' => 'GW',
        'hawthorn' => 'HW',
        'hawks' => 'HW',
        'dees' => 'ME',
        'demons' => 'ME',
        'melbourne' => 'ME',
        'melb' => 'ME',
        'roos' => 'NM',
        'north' => 'NM',
        'north melbourne' => 'NM',
        'kangaroos' => 'NM',
        'kangas' => 'NM',
        'port' => 'PA',
        'power' => 'PA',
        'port adelaide' => 'PA',
        'tigers' => 'RI',
        'tiges' => 'RI',
        'richmond' => 'RI',
        'saints' => 'SK',
        'st kilda' => 'SK',
        'swans' => 'SY',
        'sydney' => 'SY',
        'bulldogs' => 'WB',
        'doggies' => 'WB',
        'dogs' => 'WB',
        'western bulldogs' => 'WB',
        'footscray' => 'WB',
        'eagles' => 'WC',
        'west coast' => 'WC',


        // Historical teams
        'fitzroy' => 'FI',
        'brisbane bears' => 'BB',
        'bears' => 'BB',
        'bloods' => 'SM',
        'south melbourne' => 'SM',
        'university' => 'UN'
    ],
];